<template data-slot="title">Search | Joey Guerra</template>
<template data-slot="canonical">https://joeyguerra.com/search.html</template>
<h2>Search results for: {{query}}</h2>
<ol>
    {{#each results}}
    <li class="spotlight-item">
        <header>
            <a href="{{link}}" class="title">{{title}}</a>
            <p class="desc">{{excerpt}}</p>
        </header>
        <span class="badge">{{type}}</span>
    </li>
    {{/each}}
</ol>
{{#unless results}}
<p>No results found.</p>
{{/unless}}
